### ISSUE TITLE
3 Lipsum Paragraph substitution is undefined after 2 paragraphs

### ISSUE THREAD

**Issue by jcfariadias** [holidaypirates/nucleus#17]
If I use a substitution flag and point more than 2 paragraphs of Lipsum, after the 2nd paragraph, I get "undefined" text until the end of it. 
Also, the paragraphs do not break line after each one.

Example 
```CSS
/**
 * @atom Paragraph 1
 * @section Typography > Paragraphs
 * @markup
 *     <p class="paragraph--1">@{lipsum:3:paragraph}</h6>
 */
.paragraph--1{
    font-size: 14px;
    line-height: 22px;
}
```

Output 
![captura de ecra 2016-08-26 as 15 20 38](https://cloud.githubusercontent.com/assets/2012680/18008709/1946ecfa-6ba1-11e6-801d-906b2690bcb7.png)
