### ISSUE TITLE
If I do not specify a description, I get "false" printed on its place

### ISSUE THREAD

**Issue by jcfariadias** [holidaypirates/nucleus#18]
If I do not specify any description for any kind of element, I get "false" on the place where the description is supposed to be. I think that to specify a description for each block is unnecessary as sometimes, the title is self explanatory (as is with the image I'm uploading)

Example CSS
```CSS
/**
 * @atom Heading 1
 * @section Typography > Headings
 * @markup
 *     <h1>@{lipsum:1:paragraph}</h1>
 */
h1{
    font-family: 'Arial';
    font-weight: bold;
    font-size: 32px;
    line-height: 40px;
}
```

![captura de ecra 2016-08-26 as 15 26 24](https://cloud.githubusercontent.com/assets/2012680/18008912/edc03c5c-6ba1-11e6-9560-7b6233a359ba.png)
